title: Roi's Digital Territory
author: roijaboi
subtitle: My life as you know it.

url: "https://www.roijacob.com"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/roijacob"
footer_text: "Digital Home of Roi Jacob"

profile-picture: assets/profile.jpg
favicon_location: assets/icon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://github.com/roijacob"
