title: Roi's Digital Territory
author: roijacob
subtitle: Digital Real Estate of Roi Jacob Olfindo.

url: "https://www.roijacob.com"
baseurl: ""

footer_only_homepage: true
footer_url: "https://www.linkedin.com/in/roi-jacob-olfindo"
footer_text: "Created by: Roi Jacob Olfindo"

profile-picture: assets/profile.jpg
favicon_location: assets/icon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "GitHub"
   absolute-link: "https://github.com/roijacob"
